### ISSUE TITLE
Where can I find the Redux Framework Instance

### ISSUE THREAD

**Issue by mstoic** [katzwebservices/EDD-Redux-Extension#1]
I want to use the EDD field, but I am not aware where should I put the code given by you

**Comment by zackkatz** [comment]
See http://docs.reduxframework.com/core/getting-started/

**Comment by mstoic** [comment]
Still didn't got where to put this code:

$args['edd'] = array(
    'mode'            => 'template', // template|plugin
    'path'            => '', // Path to the plugin/template main file
    'remote_api_url'  => 'http://shoestrap.org',    // our store URL that is running EDD
    'version'         => "2.0.1",  // current version number
    'item_name'       => "Shoestrap 3",      // name of this theme
    'author'          => "Aristeides Stathopoulos, Dimitris Kalliris, Dovy Paukstys",    // author of this theme
    'field_id'        => "edd", // ID of the field used by EDD
    );
